# BCM2835 Platform Support
snd-soc-bcm2835-i2s-objs := bcm2835-i2s.o

obj-$(CONFIG_SND_BCM2835_SOC_I2S) += snd-soc-bcm2835-i2s.o

snd-soc-rpi-wsp-objs := rpi-cirrus-sound-pi.o
snd-soc-iqaudio-dac-objs := iqaudio-dac.o

obj-$(CONFIG_SND_BCM2835_SOC_RPI_CODEC_WSP) += snd-soc-rpi-wsp.o
obj-$(CONFIG_SND_BCM2835_SOC_IQAUDIO_DAC) += snd-soc-iqaudio-dac.o